version = 0.1
[default.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
stack_name = "pager"
resolve_s3 = true
s3_prefix = "pager"
region = "us-west-2"
image_repositories = []

[dev.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
stack_name = "pager"
resolve_s3 = true
s3_prefix = "pager"
region = "us-east-1"
image_repositories = []
profile = "dev"
