AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pager

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment (dev or prod)
  LogLevel:
    Type: String
    Default: ERROR
    AllowedValues:
      - DEBUG
      - INFO
      - WARN
      - ERROR
    Description: Log level (DEBUG, INFO, WARN, ERROR)
  EventRetryCount:
    Type: Number
    Default: 5
  Auth0Domain:
    Type: String
    Default: auth0.com
  Auth0Audience:
    Type: String
    Default: pager
Resources:
  EventsService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/events/template.yaml
      Parameters:
        Environment: !Ref Environment

  UserService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/user/template.yaml
      Parameters:
        Environment: !Ref Environment
        LogLevel: !Ref LogLevel
        EventRetryCount: !Ref EventRetryCount
        EventsTopicArn: !GetAtt EventsService.Outputs.TopicArn
        EventsTopicName: !GetAtt EventsService.Outputs.TopicName

  AgencyService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/agency/template.yaml
      Parameters:
        Environment: !Ref Environment
        LogLevel: !Ref LogLevel
        EventRetryCount: !Ref EventRetryCount
        EventsTopicArn: !GetAtt EventsService.Outputs.TopicArn
        EventsTopicName: !GetAtt EventsService.Outputs.TopicName

  EndpointService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/endpoint/template.yaml
      Parameters:
        Environment: !Ref Environment
        LogLevel: !Ref LogLevel

  PageService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/page/template.yaml
      Parameters:
        Environment: !Ref Environment
        LogLevel: !Ref LogLevel

  GatewayService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/gateway/gateway.yaml
      Parameters:
        Environment: !Ref Environment
        LogLevel: !Ref LogLevel
        Auth0Domain: !Ref Auth0Domain
        Auth0Audience: !Ref Auth0Audience
        AgencyServiceApiId: !GetAtt AgencyService.Outputs.ApiId
        PageServiceApiId: !GetAtt PageService.Outputs.ApiId
        EndpointServiceApiId: !GetAtt EndpointService.Outputs.ApiId
        UserTableName: !GetAtt UserService.Outputs.UserTableName

Outputs:
  ApiGatewayUrl:
    Value: !GetAtt GatewayService.Outputs.ApiGatewayUrl
    Description: API Gateway URL
