AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pager

Parameters:
  Auth0Domain:
    Type: String
    Default: auth0.com
  Auth0Audience:
    Type: String
    Default: pager
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment (dev or prod)

Resources:
  IdentityService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/identity/template.yaml
      Parameters:
        Environment: !Ref Environment
        Auth0Domain: !Ref Auth0Domain
        Auth0Audience: !Ref Auth0Audience

  AgencyService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/agency/template.yaml
      Parameters:
        Environment: !Ref Environment

  EndpointService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/endpoint/template.yaml
      Parameters:
        Environment: !Ref Environment

  PageService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/page/template.yaml
      Parameters:
        Environment: !Ref Environment

  GatewayService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/gateway/gateway.yaml
      Parameters:
        Environment: !Ref Environment
        AuthorizerFunctionArn: !GetAtt IdentityService.Outputs.AuthorizerFunctionArn
        AgencyServiceApiId: !GetAtt AgencyService.Outputs.AgencyApiId

Outputs:
  ApiGatewayUrl:
    Value: !GetAtt Gateway.Outputs.ApiGatewayUrl
    Description: API Gateway URL
