AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pager

Parameters:
  Auth0Domain:
    Type: String
    Default: auth0.com
  Auth0Audience:
    Type: String
    Default: pager
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment (dev or prod)

Resources:
  IdentityService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/identity/template.yaml
      Parameters:
        Auth0Domain: !Ref Auth0Domain
        Auth0Audience: !Ref Auth0Audience
        Environment: !Ref Environment

  GatewayService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./gateway.yaml
      Parameters:
        AuthorizerFunctionArn: !GetAtt IdentityService.AuthorizerFunctionArn

  AgencyService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/agency/template.yaml

  EndpointService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/endpoint/template.yaml

  PageService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/page/template.yaml
