package handlers

// problemDetails represents an HTTP Problem Details object as defined in RFC
// 7807.
type problemDetails struct {
	// A URI reference that identifies the problem type.
	Type string `json:"type"`
	// A short, human-readable summary of the problem type.
	Title string `json:"title"`
	// The HTTP status code generated by the origin server.
	Status int `json:"status"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	Instance string `json:"instance,omitempty"`
}

// problemDetails represents an validation instance of an HTTP Problem Details
// object as defined in RFC 7807.
type validationProblemDetails struct {
	problemDetails
	Problems []problem `json:"problems"`
}
