AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: AWS SAM template for the Pager User service.

Parameters:
  PolicyStoreId:
    Type: String
    Description: "Amazon Verified Permissions Policy Store ID"

Resources:
  ###############################################
  # API
  ###############################################
  UserApi:
    Type: "AWS::Serverless::Api"
    Properties:
      Name: "pager-user-api"
      Description: "User Microservice API"
      StageName: prod
  ###############################################
  # FUNCTIONS
  ###############################################
  UserInfoFunction:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "user-info"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: cmd/user_info
      Events:
        Api:
          Type: Api
          Properties:
            Path: /info
            Method: GET
            RestApiId: !Ref UserApi
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
      Environment:
        Variables:
          TABLE_NAME: !Ref UserTable
          REGION: !Ref AWS::Region
  InviteUserFunction:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "invite-user"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: cmd/invite_user
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref UserApi
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - verifiedpermissions:IsAuthorized
              Resource: !Sub arn:aws:verifiedpermissions::${AWS::AccountId}:policy-store/${PolicyStoreId}
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
      Environment:
        Variables:
          TABLE_NAME: !Ref UserTable
          POLICY_STORE_ID: !Ref PolicyStoreId
          REGION: !Ref AWS::Region
  ###############################################
  # DATABASE
  ###############################################
  UserTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "users"
      AttributeDefinitions:
        - AttributeName: idpid
          AttributeType: S
      KeySchema:
        - AttributeName: idpid
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
###############################################
# OUTPUTS
###############################################
Outputs:
  ApiId:
    Description: "API Gateway ID for User API"
    Value: !Ref UserApi
  TableName:
    Description: Name of the User DynamoDB table
    Value: !Ref UserTable
