AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pager Page Service

Parameters:
  Environment:
    Type: String
  LogLevel:
    Type: String
    Default: ERROR
    AllowedValues:
      - DEBUG
      - INFO
      - WARN
      - ERROR
    Description: Log level (DEBUG, INFO, WARN, ERROR)
  EventRetryCount:
    Type: Number
  EventsTopicArn:
    Type: String
  EventsTopicName:
    Type: String
Resources:
  Api:
    Type: "AWS::Serverless::HttpApi"
    Properties:
      Name: !Sub "pager-page-api-${Environment}"
      StageName: !Ref Environment

  AppFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "pager-page-service-${Environment}"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: ./cmd/app
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref EventsTopicName
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          ENVIRONMENT: !Ref Environment
          PAGE_TABLE_NAME: !Ref PageTable
          EVENTS_TOPIC_ARN: !Ref EventsTopicArn
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  WorkerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "pager-page-worker-${Environment}"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: ./cmd/worker
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref EventsTopicName
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          ENVIRONMENT: !Ref Environment
          EVENT_RETRY_COUNT: !Ref EventRetryCount
          PAGE_TABLE_NAME: !Ref PageTable
          EVENTS_TOPIC_ARN: !Ref EventsTopicArn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PageEventsQueue.Arn
            BatchSize: 10
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures

  PageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "pager-page-pages-${Environment}"
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  PageEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "pager-page-events-${Environment}"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PageEventsDeadLetterQueue.Arn
        maxReceiveCount: !Ref EventRetryCount

  PageEventsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "pager-page-events-dlq-${Environment}"

  PageEventsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref PageEventsQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt PageEventsQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !Ref EventsTopicArn

  PageEventsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref EventsTopicArn
      Protocol: sqs
      Endpoint: !GetAtt PageEventsQueue.Arn
      FilterPolicy:
        type:
          - "endpoint.delivery.succeeded"
          - "endpoint.delivery.failed"
Outputs:
  ApiId:
    Description: Page API ID
    Value: !Ref Api
