AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pager Agency Service

Parameters:
  Environment:
    Type: String
  LogLevel:
    Type: String
    Default: ERROR
    AllowedValues:
      - DEBUG
      - INFO
      - WARN
      - ERROR
    Description: Log level (DEBUG, INFO, WARN, ERROR)

Resources:
  Api:
    Type: "AWS::Serverless::HttpApi"
    Properties:
      Name: !Sub "pager-page-api-${Environment}"
      StageName: !Ref Environment

  AppFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "pager-page-service-${Environment}"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: ./cmd/app
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

Outputs:
  ApiId:
    Description: Page API ID
    Value: !Ref Api
