#!/bin/zsh

psql "postgresql://postgres:postgres@localhost:5432/pager?sslmode=disable" -f seed.sql

export ZED_ENDPOINT=localhost:50051 
export ZED_TOKEN=foobar 
export ZED_INSECURE=true 

# Assign pager-admin@pager.com as an adminstrator in the platform:platform
zed relationship create "platform:platform" administrator "user:auth0|6606e16332edd5a3975a6e9f" || true
# Assign platform:platform as the platform for Sample SAR Agency
zed relationship create "agency:8d282649-708b-4523-ab2a-122bd8739bd1" platform "platform:platform" || true
# Assign platform:platform as the platform for Sample EMS Agency
zed relationship create "agency:78c95398-3b3d-4e82-a648-0787af58a945" platform "platform:platform" || true
# Assign agency-admin@pager.com as a writer for Sample SAR Agency
zed relationship create "agency:8d282649-708b-4523-ab2a-122bd8739bd1" writer "user:auth0|6606e29442d9ec8442da383c" || true