AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: AWS SAM template for the Pager Agency service.

Parameters:
  PolicyStoreId:
    Type: String
    Description: "Amazon Verified Permissions Policy Store ID"

Resources:
  ###############################################
  # API
  ###############################################
  AgencyApi:
    Type: "AWS::Serverless::Api"
    Properties:
      Name: "pager-agency-api"
      Description: "Agency Microservice API"
      StageName: prod
  ###############################################
  # FUNCTIONS
  ###############################################
  CreateAgencyFunction:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "create-agency"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: cmd/create_agency
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref AgencyApi
      Environment:
        Variables:
          POLICY_STORE_ID: !Ref PolicyStoreId
          TABLE_NAME: !Ref AgencyTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - verifiedpermissions:IsAuthorized
              Resource: !Sub arn:aws:verifiedpermissions::${AWS::AccountId}:policy-store/${PolicyStoreId}
        - DynamoDBWritePolicy:
            TableName: !Ref AgencyTable

  ReadAgencyFunction:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "read-agency"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: cmd/read_agency
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{agencyid}
            Method: GET
            RestApiId: !Ref AgencyApi
      Environment:
        Variables:
          POLICY_STORE_ID: !Ref PolicyStoreId
          TABLE_NAME: !Ref AgencyTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - verifiedpermissions:IsAuthorized
              Resource: !Sub arn:aws:verifiedpermissions::${AWS::AccountId}:policy-store/${PolicyStoreId}
        - DynamoDBReadPolicy:
            TableName: !Ref AgencyTable

  ListAgenciesFunction:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "list-agencies"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: cmd/list_agencies
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref AgencyApi
      Environment:
        Variables:
          POLICY_STORE_ID: !Ref PolicyStoreId
          TABLE_NAME: !Ref AgencyTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - verifiedpermissions:IsAuthorized
              Resource: !Sub arn:aws:verifiedpermissions::${AWS::AccountId}:policy-store/${PolicyStoreId}
        - DynamoDBReadPolicy:
            TableName: !Ref AgencyTable
  ###############################################
  # DATABASE
  ###############################################
  AgencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: created
          AttributeType: S
        - AttributeName: modified
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: idpid
          AttributeType: S
        - AttributeName: agency_created
          AttributeType: S
        - AttributeName: agency_modified
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: type-created-index
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: created
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: type-modified-index
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: modified
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: type-name-index
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: name
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: idpid-agency_created-index
          KeySchema:
            - AttributeName: idpid
              KeyType: HASH
            - AttributeName: agency_created
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: idpid-agency_modified-index
          KeySchema:
            - AttributeName: idpid
              KeyType: HASH
            - AttributeName: agency_modified
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: idpid-name-index
          KeySchema:
            - AttributeName: idpid
              KeyType: HASH
            - AttributeName: name
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      BillingMode: PROVISIONED
      TableName: agencies
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

###############################################
# OUTPUTS
###############################################
Outputs:
  ApiId:
    Description: "API Gateway ID for Agency API"
    Value: !Ref AgencyApi
