AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pager Agency Service

Parameters:
  Environment:
    Type: String
  ApiGatewayId:
    Type: String
Resources:
  # AgencyApi:
  #   Type: "AWS::Serverless::Api"
  #   Properties:
  #     Name: !Sub "pager-agency-api-${Environment}"
  #     StageName: !Ref Environment

  AgencyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "pager-agency-service-${Environment}"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: ./cmd/app
      Timeout: 10
      MemorySize: 128
      Events:
        AgencyRoot:
          Type: HttpApi
          Properties:
            Path: /agencies
            ApiId: !Ref ApiGatewayId
        AgencyById:
          Type: HttpApi
          Properties:
            Path: /agencies/{id}
            ApiId: !Ref ApiGatewayId
# Outputs:
# AgencyApiId:
#   Description: Agency API ID
#   Value: !Ref AgencyApi
