AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pager Agency Service

Parameters:
  Environment:
    Type: String
  LogLevel:
    Type: String
    Default: ERROR
    AllowedValues:
      - DEBUG
      - INFO
      - WARN
      - ERROR
    Description: Log level (DEBUG, INFO, WARN, ERROR)
  EventRetryCount:
    Type: Number
  EventsTopicArn:
    Type: String
  EventsTopicName:
    Type: String

Resources:
  Api:
    Type: "AWS::Serverless::HttpApi"
    Properties:
      Name: !Sub "pager-agency-api-${Environment}"
      StageName: !Ref Environment

  AppFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "pager-agency-service-${Environment}"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: ./cmd/app
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AgencyTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref EventsTopicName
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          AGENCY_TABLE_NAME: !Ref AgencyTable
          EVENTS_TOPIC_ARN: !Ref EventsTopicArn
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  EventProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "pager-agency-event-processor-${Environment}"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: ./cmd/event-processor
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AgencyTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref EventsTopicName
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          ENVIRONMENT: !Ref Environment
          AGENCY_TABLE_NAME: !Ref AgencyTable
          EVENTS_TOPIC_ARN: !Ref EventsTopicArn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt AgencyEventsQueue.Arn
            BatchSize: 10
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures

  AgencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "pager-agency-agencies-${Environment}"
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  AgencyEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "pager-agency-events-${Environment}"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AgencyEventsDeadLetterQueue.Arn
        maxReceiveCount: !Ref EventRetryCount

  AgencyEventsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "pager-agency-events-dlq-${Environment}"

  AgencyEventsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AgencyEventsQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt AgencyEventsQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !Ref EventsTopicArn

  AgencyEventsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref EventsTopicArn
      Protocol: sqs
      Endpoint: !GetAtt AgencyEventsQueue.Arn
      FilterPolicy:
        type:
          # Events
          - "user.user.modified"
          - "user.user.deleted"
          - "user.user.ensure_failed"
          - "endpoint.endpoint.ensured_and_registered"
          # Commands
          - "agency.membership.create"

Outputs:
  ApiId:
    Description: Agency API ID
    Value: !Ref Api
  AgencyTableName:
    Description: Agency Table Name
    Value: !Ref AgencyTable
