name: General Pipeline

on:
  push:
    paths:
      - "**/*"
      - "!pkg/**" # Ignore changes in pkg/ directory
      - "!services/**" # Ignore changes in services/ directory

jobs:
  pipeline-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set CI status
        run: exit 0
