name: PR Opened - Pkg

on:
  pull_request:
    types: [opened]
    paths:
      - "pkg/**"

jobs:
  print-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Opened Info
        run: |
          echo "Pull request opened!"
          echo "Source branch: ${{ github.event.pull_request.head.ref }}"
          echo "Target branch: ${{ github.event.pull_request.base.ref }}"
