name: Build, Test, and Save Artifacts for Changed Services

on:
  push:
    branches:
      # - main
      - "**"

permissions:
  contents: write # Grant write permissions for tagging

jobs:
  build-and-save-artifact:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - agency
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history so origin/main is available

      - name: Check if service has changed
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main)
          if echo "$CHANGED_FILES" | grep -q "^services/${{ matrix.service }}/"; then
            echo "Service ${{ matrix.service }} has changed."
            echo "SHOULD_BUILD=true" >> "$GITHUB_OUTPUT"
          else
            echo "Service ${{ matrix.service }} has not changed."
            echo "SHOULD_BUILD=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set version for the service
        id: set_version
        if: steps.check_changes.outputs.SHOULD_BUILD == 'true'
        run: |
          # Define the tag prefix for the service
          TAG_PREFIX="services/${{ matrix.service }}"

          # Search for the latest tag for this specific service
          LATEST_TAG=$(git tag --list "${TAG_PREFIX}/*" --sort=-v:refname | head -n 1)

          if [ -z "$LATEST_TAG" ]; then
            # No tag exists, set initial version
            NEW_TAG="${TAG_PREFIX}/v1.0.0"
          else
            # Increment the latest tag for the service
            NEW_TAG=$(echo $LATEST_TAG | sed "s|^${TAG_PREFIX}/v||" | awk -F. '{$NF += 1; print "'${TAG_PREFIX}'/v"$1"."$2"."$3}')
          fi

          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> "$GITHUB_OUTPUT"

      - name: Run tests
        if: steps.check_changes.outputs.SHOULD_BUILD == 'true'
        working-directory: services/${{ matrix.service }}
        run: |
          echo "Running tests for ${{ matrix.service }}"
          go test ./...

      - name: Run build script
        if: steps.check_changes.outputs.SHOULD_BUILD == 'true'
        working-directory: services/${{ matrix.service }}
        run: |
          echo "Running build script for ${{ matrix.service }} with version ${{ steps.set_version.outputs.NEW_TAG }}"
          chmod +x ./build.sh
          ./build.sh ${{ steps.set_version.outputs.NEW_TAG }}

      - name: Create version tag
        if: steps.check_changes.outputs.SHOULD_BUILD == 'true'
        run: |
          git tag ${{ steps.set_version.outputs.NEW_TAG }}
          git push origin ${{ steps.set_version.outputs.NEW_TAG }}

      - name: Save build artifact
        if: steps.check_changes.outputs.SHOULD_BUILD == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.service }}-${{ steps.set_version.outputs.NEW_TAG }}
          path: services/${{matrix.service}}/dist

      - name: Create GitHub release
        if: steps.check_changes.outputs.should_build == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.set_version.outputs.NEW_TAG }}
          release_name: Release ${{ steps.set_version.outputs.NEW_TAG }}
          body: |
            Release of ${{ matrix.service }} version ${{ steps.set_version.outputs.NEW_TAG }}
          draft: false
          prerelease: false
