# name: Build and Test Changed Services

# on:
#   push:
#     paths:
#       - "services/**"

# jobs:
#   build-and-save-artifact:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         service:
#           - agency
#       fail-fast: false

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0 # Fetch all history so origin/main is available

#       - name: Check if service has changed
#         id: check_changes
#         run: |
#           CHANGED_FILES=$(git diff --name-only origin/main)
#           if echo "$CHANGED_FILES" | grep -q "^services/${{ matrix.service }}/"; then
#             echo "Service ${{ matrix.service }} has changed."
#             echo "SHOULD_BUILD=true" >> "$GITHUB_OUTPUT"
#           else
#             echo "Service ${{ matrix.service }} has not changed."
#             echo "SHOULD_BUILD=false" >> "$GITHUB_OUTPUT"
#           fi

#       - name: Run tests
#         if: steps.check_changes.outputs.SHOULD_BUILD == 'true'
#         working-directory: services/${{ matrix.service }}
#         run: |
#           echo "Running tests for ${{ matrix.service }}"
#           go test ./...

#       - name: Run build script
#         if: steps.check_changes.outputs.SHOULD_BUILD == 'true'
#         working-directory: services/${{ matrix.service }}
#         run: |
#           echo "Running build script for ${{ matrix.service }} with version ${{ steps.set_version.outputs.VERSION }}"
#           chmod +x ./build.sh
#           ./build.sh ${{ steps.set_version.outputs.VERSION }}
