# name: Build, Test, and Save Artifacts for Changed Services

on:
  push:
    branches:
      - main
#     paths:
#       - "services/**"

permissions:
  contents: write # Grant write permissions for tagging

jobs:
  version_increment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Get merged branch name from the commit message
      - name: Get merged branch name
        id: get_branch
        run: |
          # Extract the branch name from the commit message
          merged_branch=$(git log -1 --pretty=%s | sed -n 's/^Merge branch "\(.*\)".*/\1/p')
          echo "Merged branch: $merged_branch"
          echo "merged_branch=$merged_branch" >> $GITHUB_ENV

      # Step 3: Run the version increment script
      - name: Run version increment script
        run: |
          # Pass the merged branch name as an argument to the shell script
          bash ./scripts/branch_version.sh $merged_branch

      # Step 4: Output the version increment
      - name: Output version increment
        run: |
          echo "Version Increment: $version_increment"
