name: Services CI

on:
  pull_request:
    types: [synchronize]
    paths:
      - "services/**"
jobs:
  print-commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Commit Info
        run: |
          echo "New commit to the pull request!"
          echo "Source branch: ${{ github.event.pull_request.head.ref }}"
          echo "Target branch: ${{ github.event.pull_request.base.ref }}"
          echo "Commit hash: ${{ github.event.after }}"
