name: Services CI

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "services/**"

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45.0.3
        with:
          matrix: "true"
          dir_names: "true"
          dir_names_max_depth: "1"
          path: ./services
          files_ignore: "authorization/**"

  lint-and-test:
    needs: determine-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.determine-changes.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: Test package
        run: |
          cd ./services/${{ matrix.directory }}
          go test ./...

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: SAM build
        run: |
          sam build

      - name: SAM validate
        run: |
          sam validate --lint

      # TODO: establish a development environment to deploy to
      # - name: SAM deploy
      #   run: |
      #     sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

      - name: Upload SAM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sam-build
          path: .aws-sam/build

  # This allows us to have a branch protection rule for tests and deploys with matrix
  ci-status:
    runs-on: ubuntu-20.04
    needs: [build]
    if: always()
    steps:
      - name: Successful build
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failed build
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
