# name: Build, Test, and Save Artifacts for Changed Services

on:
  push:
    branches:
      - main
#     paths:
#       - "services/**"

permissions:
  contents: write # Grant write permissions for tagging

jobs:
  version_increment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run the version increment script
      - name: Run version increment script using merged branch name
        env:
          merged_branch: ${{ github.event.pull_request.head.ref }}
        run: |
          # Pass the merged branch name as an argument to the shell script
          ./scripts/branch_version.sh $merged_branch

      # Step 3: Output the version increment
      - name: Output version increment
        run: |
          echo "Version Increment: $version_increment"
