name: Services CI

on:
  push:
    paths:
      - "services/**"
  # pull_request:
  #   paths:
  #     - "services/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["agency"]
    steps:
      - name: Checkout code # Each job must check out the code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: Build Service
        if: contains(github.event.pull_request.changed_files, 'services/${{ matrix.service }}/')
        # working-directory: ${{ github.workspace }}/services/${{ matrix.service }}
        # run: ./build.sh
        run: ls -la
